### ISSUE TITLE
[BUG] Type a one-liner describing the issue here

### ISSUE THREAD

**Issue by noplex-nplx** [Switcheo/zilswap-webapp#89] opened 2021-07-11 22:24 UTC
Bugs.
- Unreadable zil and eth balance on zilswap. So can't swap zil to zilswap.
- Even if the balance is not read, you can still bridge and confirm transactions. Example: zil to eth. But the problem is that the zil balance decreases and the eth balance does not increase, and vice versa.
Before bridge
- zil balance :10000
- eth balance : 5
Smartphone
- Realme
- Android 10
- Kiwi Browser
![Screenshot_2021-07-12-04-52-10-09_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/82057437/125211530-3038c080-e2d1-11eb-86e1-cda1725becd0.jpg)
![Screenshot_2021-07-12-04-52-21-79_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/82057437/125211536-3af35580-e2d1-11eb-8e2a-ef2932fa2a59.jpg)
![Screenshot_2021-07-12-04-52-29-04_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/82057437/125211537-3c248280-e2d1-11eb-96c7-be21d0b7cefc.jpg)
![Screenshot_2021-07-12-05-21-13-18_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/82057437/125211538-3cbd1900-e2d1-11eb-9b67-fed684a671d6.jpg)

**Comment by RavenXce** [comment] 2021-08-13 02:45
Duplicate of #78 and #83.

**Closed by RavenXce** 2021-08-13 02:45 UTC
Labels: duplicate
