### ISSUE TITLE
[BUG] Bridge: Balance does not show up at times even after wallet is connected

### ISSUE THREAD

**Issue by thundahbolt** [Switcheo/zilswap-webapp#99] opened 2021-07-26 03:44 UTC
**Describe the bug**
Sometimes the wallet balance does not show up even after the wallet has been connected,

**To Reproduce**
1. Connect wallet

**Expected behavior**
Balance should show up consistently.

**Screenshots**
![image](https://user-images.githubusercontent.com/79690752/126930002-7641fce2-8085-49ba-82b2-8e317eb81a05.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Comment by RavenXce** [comment] 2021-08-13 02:50
Duplicate of #78 and #83.

**Closed** 2021-11-02 07:50 UTC
Labels: bug, duplicate
